language: node_js
node_js:
- '10'
- '8'
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@latest
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
jobs:
  include:
  - stage: eslint
    name: eslint
    script: npm run eslint
  - stage: Unit tests
    script:
    - npm run test
  - stage: publish
    if: tag IS present
    script: npm publish
env:
  global:
    secure: L5LGfp+4OP9UhvaAs7UUiJd6/g2Jj9b4gjQ30JcFRXfUXmSzHX+xjPQ3MF9mVUJMTHPwQeK3q96LlsZrmAZEi25+jhIT92JMorYEmSY+uKuYCkKyfgwKbzXHWVFOjtMCKGjg1hIbIJdrd9V5TP2YgCI/60id4SQ7s/ZhCCQx/vcW0zZiSGdqZ++WPyoSF5WqK0NZDbMBF0JbyneVDjJfwgEv8yedgUmN6c93a/K0C/ztTKEWvaUmZDaGBbbVBOAbK4vgBhsNqHGP8NjhNtTg9tR+ePhiatyiTOQdd/0p4e9lyjvAcuuDI5+ylanAw4Pu96H/C0GLGLckrLA/Qln9XCYdKSLOwZ0KopAAJSYkCAdcZEWxf8/I4anVnzl7FUrjp6k2kZcV/cfSFcxULHbX5QB7Gv++27rKUNzfNDAuAcURElUf06Wf94F2brJu7ZWKWAnOLRIrA0MBrvKSpsqNPHoVwINhLqTSOr8ZSz/J9qRWQduN4xoPbGNL33gzr1dZ/lhMCGBRlCZ0YPze6aT3W5uQ4RYuK5ccvX3lPdbKg1HTLA53M7QSh5/5aCSOtrF/GdkSNJw5k9gt2Hlfcdxr/KY2ZIoYWEsJwhSqIb6BwYdIFkAPjvjtsaVuvRO0+p/dZWzpgcmBh65GXdKonTZpL6d406MpQOfNQ5q3+wH0W18=
