language: node_js
node_js:
- 10.15.3
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.9.0
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
env:
  global:
    secure: hOCyEudoB8rm1jAAgJqaE9KkS4Yth/aoQliPnCWygTVsHyoyJrQjZnhEvfw2mOiXIuMG9BJ3N746DyAXCYYO0uurdtRnu2Fu7xavmQ31Do2gS6Y0ChPdlEf9G/ns7TAmpB3mx7bYEUKCYkyXcb9BeqNxW4wK0ubjf02LHQPMEjto4GNKxK6EaBql7VT47kFEGsXLV9yHNftRVoz7SVSTziv671YBaVlvGLchaG11yJuGdOwAS0v9iJGdk/7J5coC6mi2GJH5HzZus8h7KFpOdvt0IU/3xlGbbkudBgTI7p8vdeIiadrlHq7AKtbA0DSnV7DBQfJm5wzGq7mqrmzYa5MhXoJaVPxLwusuPKiFNi3Ktq2PCBcqkhbWIomakTcqqNv7kbXMZ2UUhp84AoPoAGdRnGH5zosFj43pOwIJBiuWy3hgyKMzBPKz4zAqd0vOKnGQ8bAi5ASLyHA6CVLIhCTKi4Zy+3QFvJIYVmR8bp52CZwrDaQF5xLAaoH9I9T2ACxSXo1LT6/sdPPv9S75aZjXB0pGVm/BzPVnuqTtO9EQt7q6+GOXbQstvKzoL2M32FS4TpDGa9LjgzHGOSloBEE8lj00nrnS1+9AZFK+BD22Sb5bnso07DmZ1f4JAwwKu7ZB27HNavmnMVUX2TqJBnzzGtZ9VlwsYowGgPUoR7E=
jobs:
  include:
  - stage: tests
    name: lint
    script: npm run eslint
  - name: unit tests
    script: npm run test-unit
  - name: integration tests
    script: npm run test-integration
  - stage: Deploy Staging
    script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - mkdir $TRAVIS_BUILD_DIR/upload
    - cp -r src build
    - cp -r bin build
    - cp package.json build
    - cp package-lock.json build
    - mv .codedeploy/appspec.yml build/appspec.yml
    - mv .codedeploy/ build/
    - cd build; tar -czvf $TRAVIS_BUILD_DIR/upload/tracker-${TRAVIS_JOB_ID}.tar .;tar
      -czvf $TRAVIS_BUILD_DIR/upload/latest.tar .;
    - cd $TRAVIS_BUILD_DIR;
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: iGtMZxN+fvrqkMM5VP86eb8GrYXtx7fas7nLKcGsZde1iikO85vLeP8dR/yIARnZ8I044EDxhETbIDUsw0Y3+uW/num9a2xehoKIV19YEr7B+yyxp0wJNEfmBR6EYOq77XR+7BGLNyxdkFVHSfU51WsmU3JjVd4kCxvgSbjraj9/NVp/EJ/4+WqbTiWaOinJSiqtyVxnRkJ4ofqz+ZG5UzFXChAIhDC0rgN5ZhCz1uBl1ofuJ+8ULQODSj4v0zeU4OFkhOCIyk92ujRFf9qZWHVwNN0fRs/qfusyN5jjf9kffebMGOhrzEG0KT6iyUp81gZX80k24+73G1KfeZKy7q2vrJ0gX+II8MOyjv77bU4ohPWpBlDsxicoSg1AiJcaPjq/42tQnA/Rcw+u60X91QTvufgHouTkkFK81/HLNkCuUbfQX5hghUyx+/Az3+4YvQ98ZPzjnMnPGcblI2iM9O5C+T05dsreBPGQMIcjVoIhlbNeNgk5VXq5OteqpAV1t9jMOfy/b6t5NtlCBBfJTFzTvGggIW4dsFAZ2Fbn4nZCyHhtinjZoysIwp9MyO9aOvcGCHuiTZh0OcEUxTtxMq6Hkk0Qwp4sw98Cj8f59fL6hrjU39s7FCWxozCDTxO9Q43JQ8gjzex+vC3Vl00UD54PTwWfnWynLsJwHzXqmSA=
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: tracker-node/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: upload
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: iGtMZxN+fvrqkMM5VP86eb8GrYXtx7fas7nLKcGsZde1iikO85vLeP8dR/yIARnZ8I044EDxhETbIDUsw0Y3+uW/num9a2xehoKIV19YEr7B+yyxp0wJNEfmBR6EYOq77XR+7BGLNyxdkFVHSfU51WsmU3JjVd4kCxvgSbjraj9/NVp/EJ/4+WqbTiWaOinJSiqtyVxnRkJ4ofqz+ZG5UzFXChAIhDC0rgN5ZhCz1uBl1ofuJ+8ULQODSj4v0zeU4OFkhOCIyk92ujRFf9qZWHVwNN0fRs/qfusyN5jjf9kffebMGOhrzEG0KT6iyUp81gZX80k24+73G1KfeZKy7q2vrJ0gX+II8MOyjv77bU4ohPWpBlDsxicoSg1AiJcaPjq/42tQnA/Rcw+u60X91QTvufgHouTkkFK81/HLNkCuUbfQX5hghUyx+/Az3+4YvQ98ZPzjnMnPGcblI2iM9O5C+T05dsreBPGQMIcjVoIhlbNeNgk5VXq5OteqpAV1t9jMOfy/b6t5NtlCBBfJTFzTvGggIW4dsFAZ2Fbn4nZCyHhtinjZoysIwp9MyO9aOvcGCHuiTZh0OcEUxTtxMq6Hkk0Qwp4sw98Cj8f59fL6hrjU39s7FCWxozCDTxO9Q43JQ8gjzex+vC3Vl00UD54PTwWfnWynLsJwHzXqmSA=
      bucket: eu-west-1-stg-streamr-vault
      key: tracker-node/releases/tracker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-tracker-node-codedeploy
      deployment_group: eu-west-1-stg-tracker-node-deployment-group
      region: eu-west-1
  - stage: publish
    if: tag IS present
    script: npm publish
