language: node_js
node_js:
- 10.17.0
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.13.0
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
jobs:
  include:
  - stage: Tests
    name: eslint
    script: npm run eslint
  - stage: publish
    if: tag IS present
    script: npm publish
env:
  global:
  - secure: r+3s8t3ijlf8opMORxEESeYpoe8WKqJjAc0c9Qi0Ll6DsxNhJ/w5ietldPHudAUwqMLUE3DyPfyPYxQp4JKOn2/CvudDxipmWtpm3EGCKEcNYaxFUv+g80dPbqeIWUcSXkFhcJozVEsB/Kv+Hj4DekxDnmY49IYfmZuM1njc0O1wDbkSyXIE3nNljn0Tz/FwRJoN0DIY91SRNhetjW5AQmJtvDtvbt6U1ROI2HbcPXl84mIJJuX3tcpNFpVIXZk8SVpl0KRoPJ8l36OBKycR4iJrf8xiwzxhTSkKKFZd5yyhHLo/F3kynGw70TQBcfO6cGUUwk6YxyQf0N2it8d4rLhj1iUVqsR/P4DaQPnQxqIjXLaGbCzs66SgrjK3NQ/5ExxvKkpUbnH+UTMnpFZwFM08ZWWRvbSLw9BTBDJv99rlgUPGm5uGcaYqNBHHj5VT5wZkjzy0gUtjbEPmVy+WEGAUk8PL0ejjmK9QVoLyrUPOtcJQyYzuiJzBjOdekqZKkPu9Zx1vfecvynFBesqwZ2CalLw5Wdw4o0ZGQblUeAHhTFVEn8S8i31lPixf8qPWQw51mb2I6oRNWI0SE24d8VyPeqUviRXAwyuiEItnihqs+nT+WQqzwZLp+7QqafpUu0vNDyhQdXKd/c7x1XWeFKgT86ew7AHYDLLvcaPRupw=
