language: node_js
node_js:
- 10.15.3
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.9.0
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
env:
  global:
  - secure: opL3vm0mTZl9g9TI+53d04AlTVYq7OA38WUMJQJWHVgPmmyfobOoFvT6+9xDXzbnh4NAgXrqtJGOxnQKkK2o+gyT2e78dLWZx1RfeeLwntgVCTEYLl844tOtgc1bwivy7ND9HfPam1yfBjYQ6UmpsgkILrPbzzHfcDwWvFXLHANk/3IiCE705gtvdC5c1/JXdUtzhYmpmsQ9JOkAg0+n6qmNvYwU7VrIixogojnEP0U3yDSbwJ+yPiWNzZpnwwe4jI/G1KE193rbEQjEOURGiyoxeyBrFOANDYT5BohRGjwsi2MTs/PEl9WDXlNfliOadtjUFI0Y3ByatLpPzWzz5aVVSxifW1YbG+WbVfqw7S4VP3ebnsHiY5uFm0f1o6wVLlNFdQtRxVi1w8mSi90C7hqs3SjFQWtStGYhiNOnqYGpSz74HOEojTUdIsT9DqOXE7tVIdH/PcnNAflHG5kbvNPv8sW5FX4Vw2ECCuT73LuYXYZ+aW0ykogFcsP84rX6yw4P4z+VS758zJ7LeJapxXzS5C0lGR9ISzg91/tSR+4RhsurwRPPRGntQULm9WBfE6QKTPxfFE8/Pprxm2kPWt3svrsNBdCgR4nTEaYF1AbX2SRQJZ4gcJF5ojfkCaP9s3YtTedJ3aV7070OoT7qReksz4A3QSKpc75uTKR8yQ8=
jobs:
  include:
  - stage: tests
    name: lint
    script: npm run eslint
  - name: unit tests
    script: npm run test-unit
  - name: integration tests
    script: npm run test-integration
  - stage: publish
    if: tag IS present
    script: npm publish

