language: java
os: linux
dist: xenial
jdk:
- openjdk8
services:
- docker
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
git:
  submodules: false
env:
  global:
  - NODE_VERSION=12
before_install:
- nvm install $NODE_VERSION
jobs:
  include:
  - stage: Run all test scenarios with latest released client versions
    name: Test against :dev docker images
    script:
    - npm install
    - $TRAVIS_BUILD_DIR/gradlew fatjar
    - $TRAVIS_BUILD_DIR/.travis-scripts/start-docker-dev.sh
    - $TRAVIS_BUILD_DIR/.travis-scripts/run-test-scenarios.sh
  - stage: Run all test scenarios with latest released client versions
    name: Test against :latest docker images
    script:
    - npm install
    - $TRAVIS_BUILD_DIR/gradlew fatjar
    - $TRAVIS_BUILD_DIR/.travis-scripts/start-docker-dev.sh production
    - $TRAVIS_BUILD_DIR/.travis-scripts/run-test-scenarios.sh
notifications:
  slack:
    secure: SZudefNcd6zl6XBqmvMwwyfTLKL5Ne8RwClU5naotZWuHgy3Pg/+X6J+dIp73bgXZsYVpPXaZTgcyoexE4q3Ru2o5a20aUhIXC3lwmmp0n2Z9o2uCzJg7QeUjoxZqMOggnrQi7/ykwM/BR7epqSFqX4QXsJhGXY8ddBSnCEVoW90bx/A/vUuMikLwDJKC+5xIVcW42E4XtBfawZrORpecKbJkouqb4id6Kk7p5IH9OttHB3bTidgSTEw4lU9lxFAdvdmy78/tzbvkjRIscROuzOECVspmuyBQhJIgiIK98kyQ1avq8vN3WQ42vHjrCXC84J6hVfUutVD2cK5bM0no1m/sf5xb4WiVsfh4XdYJCh9cSMFEJYpxX/mPVEiM6ygi8DzG0C+Y0W45FZStO4vPzeAOKF7YnnLg8rVWh+PJRcSoauKcdVdMTMtTJHV6FoZZinUC5Mg6p5dthME4UWvcWiHdLCOBHN9D1zitqPYY7Pu6yLtjWxPvqjVdDE1RNKPFM4aNIa/TYGrYbdfbMZq1Tm0wO6lDvIoqdcCYuSdttgxVQkpVqq4WK9kJN+YsmS/rmNPb+CgFoKgf7cSW3VEXFgByNtbR2ZJF5BKmPdene1univLXfuKpqo2Cbd0QKdnAVhuS/ryyeKo1PTQMy3PK9JNyxrwHBUMe55zCIfZfe0=
  if: branch = master
  on_success: change
  on_failure: always
  on_pull_requests: false
