language: node_js
node_js:
- 10.15.3
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.9.0
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
env:
  global:
  - secure: p2WF6vMPqlqn4tYZRZYixhfqJSTWCpihWniGrP0s2lT2HbVyPlWqLN38iiTbX+HcVgaGlT6tKIrFBRH1xsXzy1fhNhhUhX32uu1PWNoqVr2M1N3YNgnJTkVWxAzvtT6RuqzDPzj3gLfDEq/Dnx2D43CuvlwZG9fUTnvejoeZIh3Q5bFD71MlNO6U6eToZZKAzIz621x7GlO7j3qDdrjYqK+HMKwiidsdTya0qJFodiOQY9Dtqj4gUevoIn38VWAeI+1X5Qt0oOk14giYNECa9X8uwlN80y1Y/2BiR/sRz9LMZWW2NRfrOTy2CFZnTMXKfAPJOWtJm30xvv4AvLYz/HfPhhi9cBJtCgZLlJnJ/MXUdsi0fQ3VI6nunUfUE/QGiX8NgNQG7O+jtsYKpILTSWrJVTT7iPCIJMEaybSmaEvXz6/FH2tP8o+6j0WwRinKdjzbtN///+Q8kD7xUrtcSCxmssNDljkTf4bZtEHHC+WbzBoGoGopFkTQEjehpy4J4X3FSLzK53rmgxDWUsNH4AAki4QkWeE+kraM9d+5yTYorMGYiau98F5Tdd0D255YnUI0VkpU9E65K1gkTW8RC4sq5Ed7iNjVWvMS0pf0VyEV+4qUe8vg+vFHBzl2S6pXUPj0IXxjwaCdhLEr5TH/H4AtWxc4wCpNxV9Q0Gx1Qqc=
  - secure: YeV6Z77qCDUMz51FybwQ3yTxVY5oyin7RaZRomtjoyrKr4RK1M6M55UGyj2My7UdFQJbPMsGdPMouzi6G0+jmv/zgwu7KD7IxJ8RHij4aamyBTk/2JvrY7gtgSdrLTP4oOWm4uQY07DNPsvleuVXUJbXyFNHkjRaiG4KScj84Ss97BeTtMREHMR8IY6aaklRzxwFjtfhL3C6L/wIIrbpWuMGnO56JOPkOYDgU2hR5I3BCVCJTXt+cEUgFT0drwT/YhsE9exW0hXyVjCAuYu1Lgip/WJW8F4EEE8sGG/tI0dPTbMT7vzKN2gxTDTzYBk96fF3YF3/gIvUR0mbjHyK08KyqeOWL4DwtHX4ekOlSV6PU4gPV/znSiiVY9Vl1zIg66rpIOhSNxn/g0OZCAXu2WMt1xTl4ka/ReNBt2AqlDlcxjrYJT2xfnHjUJrKPVZCwySGl8S0GaUpijriKrvcjC+NAafqzBGMPcS2Vg8c/QqHcOG7DJrOFN1y6SYpKjfag9CVEKeL+jqj4fpR6afwi2r6gxPrm0283WHZOV1XzGUeumYHd3JhQqdp1fIMRMmGacQlyqJCJIfWEi7am0yOzP1qr8xm8Ffmxs0P9Ott7QHLgwErU6QWb0f7BvjidQPnrF4B6/fIAtlwuDHIgaYVGznePDkJlPSZlAOBQ0lE/t8=
  - secure: JXjOn4LlB4kLbf9Q+I6D7n6qw290twnJHkxOTYAltNUHjLScHMjKw80BEeyjw5UlE50KYxvMv8WieP9zIfjtYpBC8qHjAnOUkAtC8Yu+fk2UNOORXtrSlV6z9D4TwtYTYWNba3jxH9MgCR5J62To+NgYYEi7zef1CNNHk6sbQjFPh1DLwBZvvjNU73RaaQcFo5OaeCHbADbkQLJ/dryTlNmBNcdSk0yyZ5JAHSeY4wzSFjYFg+SlRXbqjH8In2ZLPj26gnb4cBX5V0bgS8sXNCBoVmgubVh8wq9jTitHWRXhzsSgA+ceEaOpmP3EArduiWhOQ8Alibuu004bPxGmp8cN1U70qHZcNvYYLn2bUfs2egf2940yfn9kAtHbMh/QoAjGtwfHLxdwPF+HC4dd7if0j9vdPwUtiajN62rrsk/W9icGdvQtOr/LLhCnDlk3BXnWY7N6tdPbQq3/B8I7n7EMImrKPWd5aYWa63CsocbFD8fdEDC3nJBaRcnjDEJ80c8iwry1bNY3c4ejJ3N3OLIGxFNW7CpREljZIiCAhhFJAbf+KEyATcqy3if6xVPWJr5fSP5ikgx6wEuOGjYD3dIoHc6k/6FTLOjZDXtxu3IubfvZBWtE4S3q8aNFSEnBklJH801GYCPB2HRyFSlYtTvwW0XHqSxrzdghzySNA/A=
jobs:
  include:
  - stage: tests
    name: lint
    script: npm run eslint
  - name: unit tests
    script: npm run test-unit
  - name: integration tests
    script: npm run test-integration
  - stage: Deploy Staging
    script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - mkdir $TRAVIS_BUILD_DIR/upload
    - cp -r src build
    - cp -r bin build
    - cp package.json build
    - cp package-lock.json build
    - mv .codedeploy/appspec.yml build/appspec.yml
    - mv .codedeploy/ build/
    - cd build; tar -czvf $TRAVIS_BUILD_DIR/upload/tracker-${TRAVIS_JOB_ID}.tar .;tar
      -czvf $TRAVIS_BUILD_DIR/upload/latest.tar .;
    - cd $TRAVIS_BUILD_DIR;
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: iGtMZxN+fvrqkMM5VP86eb8GrYXtx7fas7nLKcGsZde1iikO85vLeP8dR/yIARnZ8I044EDxhETbIDUsw0Y3+uW/num9a2xehoKIV19YEr7B+yyxp0wJNEfmBR6EYOq77XR+7BGLNyxdkFVHSfU51WsmU3JjVd4kCxvgSbjraj9/NVp/EJ/4+WqbTiWaOinJSiqtyVxnRkJ4ofqz+ZG5UzFXChAIhDC0rgN5ZhCz1uBl1ofuJ+8ULQODSj4v0zeU4OFkhOCIyk92ujRFf9qZWHVwNN0fRs/qfusyN5jjf9kffebMGOhrzEG0KT6iyUp81gZX80k24+73G1KfeZKy7q2vrJ0gX+II8MOyjv77bU4ohPWpBlDsxicoSg1AiJcaPjq/42tQnA/Rcw+u60X91QTvufgHouTkkFK81/HLNkCuUbfQX5hghUyx+/Az3+4YvQ98ZPzjnMnPGcblI2iM9O5C+T05dsreBPGQMIcjVoIhlbNeNgk5VXq5OteqpAV1t9jMOfy/b6t5NtlCBBfJTFzTvGggIW4dsFAZ2Fbn4nZCyHhtinjZoysIwp9MyO9aOvcGCHuiTZh0OcEUxTtxMq6Hkk0Qwp4sw98Cj8f59fL6hrjU39s7FCWxozCDTxO9Q43JQ8gjzex+vC3Vl00UD54PTwWfnWynLsJwHzXqmSA=
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: tracker-node/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: upload
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: iGtMZxN+fvrqkMM5VP86eb8GrYXtx7fas7nLKcGsZde1iikO85vLeP8dR/yIARnZ8I044EDxhETbIDUsw0Y3+uW/num9a2xehoKIV19YEr7B+yyxp0wJNEfmBR6EYOq77XR+7BGLNyxdkFVHSfU51WsmU3JjVd4kCxvgSbjraj9/NVp/EJ/4+WqbTiWaOinJSiqtyVxnRkJ4ofqz+ZG5UzFXChAIhDC0rgN5ZhCz1uBl1ofuJ+8ULQODSj4v0zeU4OFkhOCIyk92ujRFf9qZWHVwNN0fRs/qfusyN5jjf9kffebMGOhrzEG0KT6iyUp81gZX80k24+73G1KfeZKy7q2vrJ0gX+II8MOyjv77bU4ohPWpBlDsxicoSg1AiJcaPjq/42tQnA/Rcw+u60X91QTvufgHouTkkFK81/HLNkCuUbfQX5hghUyx+/Az3+4YvQ98ZPzjnMnPGcblI2iM9O5C+T05dsreBPGQMIcjVoIhlbNeNgk5VXq5OteqpAV1t9jMOfy/b6t5NtlCBBfJTFzTvGggIW4dsFAZ2Fbn4nZCyHhtinjZoysIwp9MyO9aOvcGCHuiTZh0OcEUxTtxMq6Hkk0Qwp4sw98Cj8f59fL6hrjU39s7FCWxozCDTxO9Q43JQ8gjzex+vC3Vl00UD54PTwWfnWynLsJwHzXqmSA=
      bucket: eu-west-1-stg-streamr-vault
      key: tracker-node/releases/tracker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-tracker-node-codedeploy
      deployment_group: eu-west-1-stg-tracker-node-deployment-group
      region: eu-west-1
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=tracker
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG --build-arg NPM_TOKEN=${NPM_TOKEN} .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
  - stage: publish
    if: tag IS present
    script: npm publish
