language: node_js
node_js:
- 10.15.3
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.9.0
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
jobs:
  include:
  - stage: eslint
    name: eslint
    script: npm run eslint
  - stage: Unit tests
    script:
    - npm run test-unit
  - stage: Integration tests
    script:
    - sudo /etc/init.d/mysql stop
    - git clone https://github.com/streamr-dev/streamr-docker-dev.git
    - sudo ifconfig docker0 10.200.10.1/24
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start engine-and-editor"
    - sleep 3m
    - node node_modules/@streamr/streamr-p2p-network/bin/tracker.js &
    - npm run test-integration
  - stage: Deploy Staging
    script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - mkdir $TRAVIS_BUILD_DIR/upload
    - cp -r src  build
    - cp app.js build
    - cp package.json build
    - cp package-lock.json build
    - mv .codedeploy/appspec.yml build/appspec.yml
    - mv .codedeploy/ build/
    - cd build; tar -czvf $TRAVIS_BUILD_DIR/upload/broker-${TRAVIS_JOB_ID}.tar .;
      tar -czvf $TRAVIS_BUILD_DIR/upload/latest.tar .;
    - cd $TRAVIS_BUILD_DIR;
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: network-node/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: upload
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      key: network-node/releases/broker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-network-node-codedeploy
      deployment_group: eu-west-1-stg-network-node-deployment-group
      region: eu-west-1
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      key: network-node/releases/broker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-network-node-cassandra-codedeploy
      deployment_group: eu-west-1-stg-network-node-cassandra-deployment-group
      region: eu-west-1
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      key: network-node/releases/broker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-network-node-storage-codedeploy
      deployment_group: eu-west-1-stg-network-node-storage-deployment-group
      region: eu-west-1
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=broker-node
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG --build-arg NPM_TOKEN=${NPM_TOKEN} .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
  - stage: publish
    if: tag IS present
    script: npm publish
env:
  global:
    secure: RiL1ul75w9pMGsimDPCm9OBzj8gdQZEl8jimBWpzS27/aoPOTu2Z0RkGPSaEvqOmSdcy5FsfKQUQgq9H6yesrBbDuJcN3jjm53DWmMZCua+JdoL1ySRBVMJo1oPTUTjw7seWAshVYbY6qHbG9GUcyd095wH07ykhq8aEXywl5mrrTdzyMg8+K2XvyrTBil6RzJ+bQcNtnDgksVnpGEqzqnw3iCzcgSSv25r/mlRxcggsah7lsoaOd4zHCYxl3VFcZgZRc2PYNK3BkWrarTFnTIXTEmikO9JFLoARmrBIgxJo9WEae4HYus4qy9Q+fGMxlAt3Ce55MQavQuiL9QpspPHFbvAJnur0PLGVNq6ChS4pz7C6L5dSO9QV6kVxoyVumlHExWvF4xr3mb1LQcb/Svt8DCk2cf9n//QXg3z7Em0kd77diVAoPpR00PSOVR4Y2CXXURfaVzKjTRfUV4lvVbiYR5Ox+RwsDIYLKsZZNYd2mj8Dj+5dq9RfMqk9qMYQ12ypY21dpgCDKoUdmtv7Y5+72v1OK6xRi1Hx9g2Nth2lp4mpJ2aBv4vzGJLG4DHtjv8Er8wpwmAyuSqVQmjRV75v6YintLr2Iu5aXejrtApEybiR0mGXNXRYM6iTkBnhAw8iVlC3Nk2AWpKkaPL3vWh+g6eXLlliTGHZHMxuXVM=
